sudo: false
language: node_js
node_js:
- node
install:
- npm install
script:
- npm run release
deploy:
  - provider: npm
    email: apispots@gmail.com
    api_key: $NPM_API_KEY
    on:
      branch: master
    tags: true
    skip_cleanup: true
    repo: apispots/apispots-lib-stories

notifications:
  email:
    recipients:
      - apispots@gmail.com
    on_success: never
